export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';

export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const PASSWORD_UPDATE_FAIL = 'PASSWORD_UPDATE_FAIL';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';

export const DOCUMENT_UPDATE = 'DOCUMENT_UPDATE';
export const DOCUMENT_UPDATE_FAIL = 'DOCUMENT_UPDATE_FAIL';
export const DOCUMENT_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';

export const PROFILE = 'PROFILE';

// common
export const GET_COMPANY_CATEGORIES = 'GET_COMPANY_CATEGORIES';
export const GET_DOCUMTE_CATEGORIES = 'GET_DOCUMTE_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_SUB_SERVICES = 'GET_SUB_SERVICES';
export const GET_STATES = 'GET_STATES';
export const GET_DISTRICTS = 'GET_DISTRICTS';
export const GET_MUNICIPALITIES = 'GET_MUNICIPALITIES';

// proposal
export const PROPOSAL_REQUEST = 'PROPOSAL_REQUEST';

// Investor
export const INVESTOR_SIGNUP = 'INVESTOR_SIGNUP';
export const INVESTOR_SIGNUP_FAIL = 'INVESTOR_SIGNUP_FAIL';
export const INVESTOR_SIGNUP_SUCCESS = 'INVESTOR_SIGNUP_SUCCESS';

// clear message
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
